---

  - name: "create backup directory"
    file: >
      path={{ backup_path }}
      state=directory
      owner={{ access_user }}
    tags: configuration
    become: yes
    become_method: sudo

  - name: "create bin directory"
    file: >
      path={{ bin_directory }}
      state=directory
      owner={{ access_user }}
    tags: configuration

  - name: install s3cmd utility
    apt: pkg=s3cmd state=installed
    become: yes
    become_method: sudo

  - name: Write S3 Configuration credentials
    template: src=s3cfg.j2 dest=/home/{{ access_user }}/.s3cfg

  - name: Write backup script
    template: src=backup.j2 dest={{ bin_directory }}/backup.sh

  - name: Write restore script
    template: src=restore.j2 dest={{ bin_directory }}/restore.sh

  - name: Write crontab
    cron: name="run backup" minute="0" hour="0" day="*/1" job="sh {{ bin_directory}}/backup.sh"
